services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=portfolio'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'

  chat-service:
    image: 'anilogutveren/chat-service:latest'
    depends_on:
      - pgvector
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pgvector:5432/portfolio'
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'password'
